import {
  Server,
  Container,
  Zap,
  Box,
  Monitor,
  Database,
  HardDrive,
  Cpu,
  FolderOpen,
  Scale,
  Network,
  Globe,
  Shield,
  AtSign,
  User,
  Chrome,
  Smartphone,
  Wifi,
  Cloud,
  CloudCog,
  CloudLightning,
  Layers,
  ListOrdered,
  Radio,
  Rss,
  Webhook,
  Link,
  FileJson,
  Cable,
  type LucideIcon,
} from "lucide-react"

interface IconProps {
  className?: string
}

export const iconMap: Record<string, LucideIcon> = {
  server: Server,
  container: Container,
  lambda: Zap,
  kubernetes: Box,
  vm: Monitor,
  database: Database,
  nosql: HardDrive,
  cache: Cpu,
  storage: HardDrive,
  filesystem: FolderOpen,
  loadbalancer: Scale,
  apigateway: Network,
  cdn: Globe,
  firewall: Shield,
  dns: AtSign,
  user: User,
  browser: Chrome,
  mobile: Smartphone,
  iot: Wifi,
  aws: Cloud,
  gcp: CloudCog,
  azure: CloudLightning,
  cloud: Layers,
  queue: ListOrdered,
  eventbus: Radio,
  pubsub: Rss,
  webhook: Webhook,
  http: Link,
  rest: FileJson,
  graphql: Network,
  websocket: Cable,
}
